### ISSUE TITLE
Update TwentySeventeen

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-skeleton#25]
The currently included version of TwentySeventeen is `1.3`, but the [current released](https://wordpress.org/themes/twentyseventeen/) version is `1.7`.

Can this be a straight swap?

**Comment by GaryJones** [comment]
Related: https://github.com/Automattic/vip-go-skeleton/pull/16 (where TwentySeventeen was updated to 1.3)

**Comment by mjangda** [comment]
Yep, makes sense to update. Can you open up a PR?
