### ISSUE TITLE
Add sample .vip.yml

### ISSUE THREAD

**Issue by uxcitizen** [Automattic/vip-go-skeleton#27]
What do you think of the idea of adding a sample config/.vip.yml config file for domain mapping? It could help clarify the syntax required. 

https://vip.wordpress.com/documentation/vip-go/syncing-data-on-vip-go/#domain-mapping-config

I was thinking the code could be commented out. Would it screw anything up with the sync process, however, if the sync finds the file and there's nothing in it?

If you like this idea, I'll create a PR.

**Comment by mjangda** [comment]
> It could help clarify the syntax required.

My main question would be: how can we improve the docs instead to make things clearer?

Beyond that I guess I'm not totally opposed to having a `config/.vip.sample.yml` file.

**Comment by uxcitizen** [comment]
That's a good question - when I read the docs they seem pretty clear to me, but I've encountered a number of folks who've been confused...

**Comment by mjangda** [comment]
Going to close this out for now in the interest of keeping things lean. Docs are a good start for now and we can revisit if needed.

**Comment by uxcitizen** [comment]
fine by me - I think since it's been in the UI I've seen less client confusion. :-)
