### ISSUE TITLE
Include deployment tooling and local development environment 

### ISSUE THREAD

**Issue by kasparsd** [Automattic/vip-go-skeleton#38]
The current skeleton repository leaves a lot of questions unanswered, for example:

- How to create a standardised local development environment that matches the [VIP Go setup](https://vip.wordpress.com/documentation/vip-go/understanding-your-vip-go-codebase/) without everyone on the team [doing it manually](https://vip.wordpress.com/documentation/vip-go/local-vip-go-development-environment/).

- How to include built JS/CSS files or PHP libraries that are normally excluded from Git tracking?

- How to deploy changes to VIP Go staging and production environment, preferably automatically after merging to `develop` or `master`?

We've created this [VIP Go project template](https://github.com/xwp/vip-go-site) which includes tooling for deploys, managing dependencies and also a local development environment.

Would any of that be useful for this default project skeleton?

**Comment by mjangda** [comment]
That project template is super cool @kasparsd!

In the past, we've tried to avoid being too opinionated with what we include in the skeleton opting to keep it lean. We see lots of different workflows, requirements, and skill levels; and so far it hasn't made sense to include too many additional dependencies and tools

But we're definitely not opposed to it either. The Local Development piece looks very interesting as does the deployment script. We'll take a closer look and follow-up.

**Comment by kasparsd** [comment]
Thanks @mjangda!

> In the past, we've tried to avoid being too opinionated with what we include in the skeleton opting to keep it lean.

You've seen way more examples of various workflows that teams use for VIP Go so I'm sure there are many things I haven't considered.

I think there are two purposes of the current VIP Go skeleton:

1. To provide a starting point for VIP internally to get new projects running on the VIP servers.

2. To provide tools, workflows and best practices for developers working on projects hosted by VIP Go. 

The current repository serves the first purpose relatively well. However, it leaves developers in the dark for how to actually do things in a way that is simple, predictable and scalable as the project evolves.

The VIP Go client repositories hosted at @wpcomvip are used for tracking the final production code which is then ingested by the platform and deployed to the actual servers -- essentially a storage medium that just happen to be accessible over git. So those repositories shouldn't be used for the actual development as they include all the build files and project artifacts. They _do_ require a specific file structure but otherwise are agnostic to how the code gets there.

For example, here is [a project template for running WordPress on Pantheon](https://github.com/pantheon-systems/example-wordpress-composer) -- it includes everything a team would need to start deploying code to their platform. It doesn't include a development environment but it does have instructions on how to set it up with Lando.

That is a very helpful project skeleton because it provide sane defaults for everything. It also probably reduces support burden for the commonly asked questions since they're included in the project template.

I'm really passionate about developer experience and workflow automation which is why I would love for VIP Go to be the easiest platform for hosting enterprise level solutions built with WordPress.

**Comment by kasparsd** [comment]
Closing since VIP now has dedicated local development tooling https://docs.wpvip.com/technical-references/vip-local-development-environment/
