### ISSUE TITLE
Fix Incorrect wording Change `true` to `false` on vip-go-skeleton/blob/master/vip-config/vip-config.php#L36

### ISSUE THREAD

**Issue by amandasjackson** [Automattic/vip-go-skeleton#87]
According to our documentation here:

https://docs.wpvip.com/technical-references/restricting-site-access/controlling-content-distribution-via-jetpack/#h-enabling-content-distribution

This line should read  `You can disable "private" mode (e.g. for testing) in non-production environment by setting the constant to `false` below (or just by removing the lines).`

Currently it says to set the constant to `true`

https://github.com/Automattic/vip-go-skeleton/blob/master/vip-config/vip-config.php#L36

This has caused some confusion with a customer in 152061-zen

**Comment by jesse-greathouse** [comment]
A fix has been entered for merge in PR #88
